### ISSUE TITLE
ValueError: Length mismatch: Expected axis has 192 elements, new values have 193 elements

### ISSUE THREAD

**Issue by mattsmith321** [AleksLi1/Accelerating_Dual_Momentum#1]
When I run the code as-is from the repo, I am getting the following error:
```
[*********************100%***********************]  4 of 4 completed
[*********************100%***********************]  1 of 1 completed
Traceback (most recent call last):
  File "D:\Users\Matt\Documents\python\adm\main.py", line 83, in <module>
    result_df.index = trading_month_start
  File "C:\Users\Matt\AppData\Roaming\Python\Python310\site-packages\pandas\core\generic.py", line 5588, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\Matt\AppData\Roaming\Python\Python310\site-packages\pandas\core\generic.py", line 769, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\Matt\AppData\Roaming\Python\Python310\site-packages\pandas\core\internals\managers.py", line 214, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "C:\Users\Matt\AppData\Roaming\Python\Python310\site-packages\pandas\core\internals\base.py", line 69, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 192 elements, new values have 193 elements
```

I can make the error "go away" by updating line 82 to:
```
trading_month_start = trading_month_start[7:]
```

But then it throws a similar length mismatch error on the next section.

I could start hacking away to try to make it work but hoping you are already aware and have a fix.

Thanks!

**Comment by AleksLi1** [comment]
Hi Matt,

Apologies for the radio silence, these models are a bit of a hobby for me and with work I haven't had the chance to take a look at your issue.

As I understand this issue stems from an adjustment being made to the length of the trading_month_start list (trading_month_start = trading_month_start[6:]), which breaks if we import data from different dates than originally intended. I'm working on a fix, and hopefully today I'll be able to push it to git.

I'll close this thread once this is done.

Thank you for your patience,
Aleks

**Comment by AleksLi1** [comment]
Hi Matt,

I've pushed an update to the project that gets rid of this issue. 

However, there seems to be some other issues related to the performance of the model itself, which I will be looking into over the next couple of days. 

Let me know if anything else catches your eye.

Thanks,
Aleks
